#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# If a monitor is connected in HDMI then use the first config else use the second one
if [[ $(xrandr -q | grep "HDMI-1-1 connected") ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rate 60.01 --rotate normal --output HDMI-1-1 --rate 75.0 --mode 1920x1080 --rotate right --right-of eDP-1
    bspc monitor eDP-1 -d I II III IV V
    bspc monitor HDMI-1-1 -d VI VII VIII IX X
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --rate 144.0 --rotate normal
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

nitrogen --restore

bspc config border_width		0
bspc config window_gap			1
bspc config focused_border_color \#3c3836
bspc config normal_border_color \#1d2021
bspc config pointer_mod         mod4
bspc config pointer_action1     move
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1'
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on
#bspc rule -a polybar border=off manage=off

setxkbmap -option caps:swapescape # Swap ESC and CAPSLOCK
xset r rate 180 100 # 180 is the delay until next click to consider that as repeated click, 90 is the speed
redshift -P -O 5000

$HOME/.config/configs/polybar/launch.sh
