#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		0
bspc config window_gap			1		 
bspc config focused_border_color \#3c3836
bspc config normal_border_color \#1d2021
bspc config pointer_mod         mod4
bspc config pointer_action1     move

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on

bspc rule -a polybar border=off manage=off

#Autostart
feh --bg-scale /home/rishad/Pictures/rust_wallpaper.png

# Swap ESC and CAPSLOCK
setxkbmap -option caps:swapescape

# Set Keyboard Delay Rate and Repeate Rate respectively
xset r rate 200 40

polybar &
