# Set the path to the oh-my-zsh installation directory
export ZSH="/usr/local/share/.oh-my-zsh"

# Set the agnoster theme as the default zsh theme
export ZSH_THEME="agnoster"

# Enable case-sensitive tab completion and command correction
export CASE_SENSITIVE="true"
export ENABLE_CORRECTION="true"

#export ZSH_AUTOSUGGEST_STRATEGY="match_any"

# Configure the highlight style for zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ebdbb2,bg=#282828,bold,underline"

# Configure the autosuggest strategy for the zsh-autosuggestions
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

#export PATH="$HOME/.local/logseq:$HOME/.local/share/fnm:$PATH:"
export PATH="/home/rishad/go/bin:/home/rishad/.local/share/solana/install/active_release/bin:/home/rishad/hdd/flutter/bin:/home/rishad/hdd/android_flutter/android-studio/bin:/home/rishad/hdd/android/sdk/platform-tools:/usr/local/bin:/home/rishad/gradle-7.6/bin:/home/rishad/hdd/android/sdk/cmdline-tools/latest/bin:/usr/local/jdk_18.0.2.1/jdk-18.0.2.1/bin:/home/rishad/.cargo/bin:/usr/local/pgsql/bin:$PATH"
export ANDROID_HOME="/home/rishad/hdd/android/sdk"

# Load the oh-my-zsh framework(globally)
source $ZSH/oh-my-zsh.sh

# Load the zsh-syntax-highlighting and zsh-autosuggestions plugins (globally)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Load the following plugins(spaces are the delimeter here)
plugins=(
    git
    zsh-vi-mode
)

# Set vi-mode keybindings
bindkey -v

# Set the keybinding for accepting autosuggestions(which is Alt + f)
bindkey '\ef' autosuggest-accept

alias cat="bat"
alias ls="exa"
alias vi="nvim"
alias vim="nvim"
alias cr="cargo run"
alias cb="cargo build"
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'

alias rm='gio trash'
