# Set the path to the oh-my-zsh installation directory
export ZSH="/usr/local/share/.oh-my-zsh"

# Set the agnoster theme as the default zsh theme
export ZSH_THEME="agnoster"

# Enable case-sensitive tab completion and command correction
export CASE_SENSITIVE="true"
export ENABLE_CORRECTION="true"

#export ZSH_AUTOSUGGEST_STRATEGY="match_any"

# Configure the highlight style for zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ebdbb2,bg=#282828,bold,underline"

# Configure the autosuggest strategy for the zsh-autosuggestions
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export PATH="/usr/local/bin:$PATH"

# Load the oh-my-zsh framework(globally)
source $ZSH/oh-my-zsh.sh

# Load the zsh-syntax-highlighting and zsh-autosuggestions plugins (globally)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Rust Aliases
alias cr="cargo run"
alias cb="cargo build"

# Set exa as the default replacement for ls
alias ls="exa"

# Set nvim as the default editor for vi and vim
alias vi="nvim"
alias vim="nvim"

# Load the following plugins(spaces are the delimeter here)
plugins=( 
    git
    zsh-vi-mode
)

# Set vi-mode keybindings
bindkey -v

# Set the keybinding for accepting autosuggestions(which is Alt + f)
bindkey '\ef' autosuggest-accept
